import "./globals.css";

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported but less commonly used
  // interactiveWidget: 'resizes-visual',
};
export const metadata = {
  title: "chatWithYou",
  description: "Generated by Angel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="min-h-full flex flex-col bg-fondo">{children}</body>
    </html>
  );
}
